name: Weekly Python Script

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    # every Wednesday at noon UTC
    - cron: '0 12 * 9-12 3'  # For September to December
    - cron: '0 12 * 1 3'     # For January

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r .github/scripts/update_script_requirements.txt

    - name: Run the script
      run: python .github/scripts/update_stats.py